<h2>Анализ выбросов</h2>

In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [4]:
data = pd.read_csv('data_big.csv')
necessary_columns = ['SBP.1', 'DBP.1', 'SV.1', 'CO.1', 'SI.1', 'CI.1', 'TPR.1']
data = data[necessary_columns]
data.fillna(data.mean(), inplace=True)
data

    SBP.1  DBP.1        SV.1      CO.1       SI.1      CI.1        TPR.1
0     116     80   74.000000   5.30000  40.000000  2.900000  1387.000000
1     144     70  168.000000  11.40000  83.000000  5.600000   663.000000
2     140     92   55.000000   5.40000  28.000000  2.800000  1598.000000
3     136     98   69.000000   3.90000  33.000000  1.800000  2292.000000
4     144     90   39.000000   3.30000  19.000000  1.700000  2592.000000
5     168     98   60.000000   6.80000  29.000000  3.300000  1426.000000
6     124     88   47.000000   5.10000  21.000000  2.300000  1567.000000
7     128     80   63.000000   4.90000  28.000000  2.200000  1566.000000
8     180     95  101.000000  10.20000  52.000000  5.300000   966.000000
9     120     78   40.000000   4.40000  24.000000  2.800000  1679.000000
10    140     90   23.000000   2.70000  12.000000  1.500000  3158.000000
11    124     74  124.000000   8.70000  66.000000  4.600000   832.000000
12    114     76  113.000000   9.10000  61.000000  4.800000   783.000000
13    156    110   59.000000   3.70000  33.000000  2.100000  2707.000000
14    160     98   59.000000   7.60000  54.000000  4.600000  1255.000000
15    116     80   39.000000   4.30000  23.000000  2.500000  1710.000000
16    124     92   55.000000   4.70000  30.000000  2.600000  1746.000000
17    130     90   49.000000   3.10000  30.000000  1.900000  2612.000000
18    124     86  135.000000   6.60000  77.000000  3.800000  1495.000000
19    126     86   89.000000   5.10000  46.000000  2.700000  1547.000000
20    148     94   58.000000   5.10000  35.000000  3.000000  1765.000000
21    152     98   94.000000   6.40000  50.000000  3.400000  1449.000000
22    126     80   58.000000   4.10000  29.000000  2.000000  1862.000000
23    142     84  101.000000   8.10000  47.000000  3.800000  1029.000000
24    152     96  101.000000   7.80000  52.000000  4.000000  1175.000000
25    140    100   32.000000   2.60000  16.000000  1.400000  3482.000000
26    144     98   76.000000   6.60000  36.000000  3.100000  1392.000000
27    166     96   67.000000   5.70000  38.000000  3.200000  1673.000000
28    160     80   77.000000   5.90000  40.000000  3.100000  1445.000000
29    160    114   48.000000   5.30000  25.000000  2.800000  1958.000000
30    146     94   73.727273   5.80303  39.272727  3.057576  1686.242424
31    144     96   96.000000   5.40000  52.000000  2.900000  1670.000000
32    160    106   75.000000   6.40000  49.000000  3.200000  1708.000000
33    162     94   89.000000   5.80000  38.000000  3.200000  1457.000000

In [7]:
#Значения статистики Фишера для каждого столбца позволяют оценить относительную изменчивость данных. 
#Если значение статистики Фишера для какого-либо столбца сильно отличается от остальных значений, 
#это может указывать на наличие выбросов в этом столбце.

def fisher_statistic(data):
    mean = np.mean(data)
    std = np.std(data)
    return (std / mean) * 100

# Применение статистики Фишера к данным
for column_name, column_data in data.items():
    column_fisher_stat = fisher_statistic(column_data)
    print(f"Статистика Фишера для столбца {column_name}:")
    print(column_fisher_stat)
    print("\n")

Статистика Фишера для столбца SBP.1:
11.904633134331506


Статистика Фишера для столбца DBP.1:
11.028932573602997


Статистика Фишера для столбца SV.1:
41.732034318318654


Статистика Фишера для столбца CO.1:
34.76622866029399


Статистика Фишера для столбца SI.1:
41.47495079456519


Статистика Фишера для столбца CI.1:
33.51360213665184


Статистика Фишера для столбца TPR.1:
36.79280835238135

In [6]:
# Функция для обнаружения выбросов
#Используется межквартильный размах для определения выбросов.
def detect_outliers(data, threshold=1.5):
    q1 = np.percentile(data, 25)
    q3 = np.percentile(data, 75)
    iqr = q3 - q1
    lower_bound = q1 - threshold * iqr
    upper_bound = q3 + threshold * iqr
    outliers = data[(data < lower_bound) | (data > upper_bound)]
    return outliers

# Проходимся по каждому столбцу и обнаруживаем выбросы
for column in df.columns:
    outliers = detect_outliers(df[column])
    if len(outliers) > 0:
        print("Столбец '{}':".format(column))
        print(outliers)
        print()

Столбец 'SV.1':
1    168.0
Name: SV.1, dtype: float64

Столбец 'CO.1':
1    11.4
8    10.2
Name: CO.1, dtype: float64

Столбец 'SI.1':
1    83.0
Name: SI.1, dtype: float64

Столбец 'CI.1':
1    5.6
8    5.3
Name: CI.1, dtype: float64

Столбец 'TPR.1':
1      663.0
4     2592.0
10    3158.0
11     832.0
12     783.0
13    2707.0
17    2612.0
25    3482.0
Name: TPR.1, dtype: float64